# Generated by Django 4.0.6 on 2022-07-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'admin'), (2, 'staff'), (4, 'chairman'), (5, 'director'), (3, 'convenor')], null=True),
        ),
    ]
